run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

issues:
  max-same-issues: 100
  include:
    - EXC0012
    - EXC0014
  exclude-dirs: []
  exclude-rules:
    - path: retry_test.go
      linters:
        - revive
      text: "this block is empty"
  fix: true

linters:
  enable:
    - bodyclose
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - typecheck
    - unused
    - whitespace

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  path-prefix: ""
  sort-results: true